lessons:
  outputs:
    dev:
      dataset: dbt_lessions_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: soy-framing-451514-f3
      threads: 60
      type: bigquery
  target: dev
